version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      #change url through postman
      - REACT_APP_API_URL=http://localhost:3001/api
  server:
    build:
      context: ./server
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - client

#docker-compose up and docker-compose down